spring:
  application:
    name: songfu-java

  datasource:
    url: jdbc:mysql://localhost:3306/songfu_java
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: 1234
  servlet:
    multipart:
      max-request-size: 100MB
      max-file-size: 10MB

mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
    map-underscore-to-camel-case: true

logging:
  level:
    org.springframework.jdbc.support.JdbcTransactionManager: debug


# 打印文件保存地址
file:
  excel-save-path: C:/Users/jxxsh/Documents/SongFuPrint/Excel/
  pdf-save-path: C:/Users/jxxsh/Documents/SongFuPrint/PDF/
  triplicate-form-template: C:/Users/jxxsh/Documents/SongFuPrint/FormTemplate/三联表单模板.ods
  quadruplicate-form-template: C:/Users/jxxsh/Documents/SongFuPrint/FormTemplate/四联表单模板.ods


jwt:
  secret: 12234243gdsgdsgsd
  expire-hours: 12

my:
  admin-password: 12345678